name: Test Deploy Docs (Wormhole)

on:
  workflow_dispatch: # Triggered manually from the Actions tab

jobs:
  call-docs-deploy:
    uses: Telucero/workflows/deploy-docs.yml@Central_repo_test
    with:
      branch: main                          # Branch to deploy from in the docs repo
      repository: Telucero/wormhole-docs
      path: wormhole-docs                   # Folder to clone the docs into
      url_prefix: wormhole-mkdocs           # Prefix used for URL rewriting
      submodules: true                      # Optional: pass true if using git submodules
    permissions:
      contents: write  # Needed to push to gh-pages
