name: Deploy Docs

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to build and deploy documentation from"
        required: true
        default: "main"

jobs:
  deploy:
    uses: Telucero/workflows/.github/workflows/deploy-docs.yml@main
    with:
      branch: ${{ inputs.branch }}
      repository: wormhole-foundation/wormhole-docs
      path: wormhole-docs
      url_prefix: wormhole-mkdocs
      submodules: true
